### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by MaxDesiatov** [microsoft/LocalizedStringKit#2]
Thanks a lot for this library, I'd be interested to integrate it into my projects, but none of those use Carthage. It would be great if LocalizedStringKit supported SwiftPM, are there any plans for that?

**Comment by dalemyers** [comment]
There's nothing official at this point, but we'd definitely merge a PR which added support 😉

**Comment by dalemyers** [comment]
Support for Swift PM was added a few weeks ago.
