### ISSUE TITLE
plural and stringsdict support

### ISSUE THREAD

**Issue by Artoria2e5** [microsoft/LocalizedStringKit#4]
People familiar with other systems will almost immediately recognize this English-as-key approach as similar to [gettext](https://en.wikipedia.org/wiki/Gettext), a Unix translation facility from the late 1980s. Such a comparison will almost immediately raise a question: where is the plural facility?

If I am not mistaken, the current form of the python tool only generates `strings` files, which has no capacity to handle plural stuff ([`NSStringPluralRuleType`](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/StringsdictFileFormat/StringsdictFileFormat.html)). For truly international programs, this is often needed since plural rules vary widely among languages. Please consider putting plural support on your TODO list.

(Python has a builtin `plistlib` library that makes dealing with plists less of a headache. You will still need to come up with a way to select the NSStringFormatValueTypeKey used for the plural though.)

**Comment by dalemyers** [comment]
You are absolutely correct on this. It's an issue we are well aware of and something we do have plans for in the future. We have nothing concrete at this point though.

**Comment by Artoria2e5** [comment]
What we want is a way to represent the [multiple plural substitutions](https://tech.smartling.com/localizing-your-ios-os-x-apps-the-right-way-stringsdict-to-the-rescue-1b90082c00ae) in one string. There actually is a string format system called [ICU MessageFormat](http://userguide.icu-project.org/formatparse/messages) that does the whole sort of stuff, and we can simplify its plural syntax to something like:

```C
Localized("{ eggs, d, one: An egg, other: %{} eggs } in { drawers, x, one: a drawer, other: %{} drawers }", "Comment here...");
```

In Python we can parse this `{VAR, FMT, one: ONE, other: OTHER}` sort of stuff. The example is meant to yield the following plist structure:

```Plist
{
    "SomeKey" = {
        NSStringLocalizedFormatKey = "%1$#@eggs@ in %2$#@drawers@";
        eggs = {
            NSStringFormatSpecTypeKey = NSStringPluralRuleType;
            NSStringFormatValueTypeKey = d;
            one = "An egg";
            other = "%d eggs";
        };
        drawers = {
            NSStringFormatSpecTypeKey = NSStringPluralRuleType;
            NSStringFormatValueTypeKey = x;
            one = "a drawer";
            other = "%x drawers";
        };
    };
}
```

(No, I am not typing the new XML plist by hand. Old style for the win.)

The documentation for [ngettext](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html) documents the interactions with string format that we should look out for. A lot of it is about how to use the POSIX `%n$fmt` format to specify ordering.

**Comment by Artoria2e5** [comment]
If I get this right, I can do this in the `dotstrings` module as an extra transformation step. After extraction by XCode it can run the parser, get the parsed entries, turn some into dict entries, and emit the new dict.

**Comment by levinli303** [comment]
@dalemyers I'm planning to add support for stringsdict in a way that is more consistent with how Apple does it. Using `%#@` like `"I ate %#@appleCount@ and %#@bananaCount@"` with no change to the Objective-C API. 

```
let str = Localized("I ate %#@appleCount@ and %#@bananaCount@", comment: "Comment for a string with cardinal numbers")
let localized = String.localizedStringWithFormat(str, 1, 2)
```

In localizedstringkit python code, we detect `%#@...%` pattern with regex from the scanner result, and generate stringsdict for these entries.
