### ISSUE TITLE
how can I use the other language

### ISSUE THREAD

**Issue by 0xMorty9** [microsoft/LocalizedStringKit#6]
The default is English ,How can I use the language such as Japanese，Spanish， French

**Comment by dalemyers** [comment]
Unfortunately at that point, this isn't supported. It would be relatively easy to add support though if you'd like to open a PR? 

First up you'd have to open one against [dotstrings](https://github.com/microsoft/dotstrings/) and modify this to allow the base language to be passed in: https://github.com/microsoft/dotstrings/blob/f642fee5e14dcba633a49e97faca40c65b29df96/dotstrings/genstrings.py#L65 Then you can modify this method https://github.com/microsoft/LocalizedStringKit/blob/057c8993366c83ab23a59d549bc6c060a945899b/generation/localizedstringkit/__init__.py#L50 to pass in a value from the command line down to `generate_strings` as the base language. 

It's likely we'd add support ourselves at some point, but it's not high on our agenda.

**Comment by 0xMorty9** [comment]
thank you
