### ISSUE TITLE
What to do after generating "en.lproj"?

### ISSUE THREAD

**Issue by haojianzong** [microsoft/LocalizedStringKit#9]
Looks like this library only [generate "en.lproj" file](https://github.com/microsoft/dotstrings/blob/f642fee5e14dcba633a49e97faca40c65b29df96/dotstrings/genstrings.py#L42). If the App supports more than 1 language, for example, Chinese, should we copy the en.lproj into zh-cn.lproj and update the strings files there?

**Comment by dalemyers** [comment]
Yeah, that's right. Everyone uses a different solution for localization so this just tries to be the lowest common denominator. It will generate en.lproj and let the consumer decide how to handle the other languages.
